### ISSUE TITLE
If the timeline is empty and meant to be shown, there is no indicator that posts are empty

### ISSUE THREAD

**Issue by zzz-acha** [paolordls/timeline-viewer#23]
To replicate:
- Create an account (either Mastodon or Bluesky) which is not following anyone (i.e. the following timeline is empty)
- Hide posts from the account which is following someone (removing the "toggle the filters" message)

The message displayed should be "no posts," but instead the page is empty.

**Comment by paolordls** [comment]
resolved by #22

**Comment by zzz-acha** [comment]
Issue still persists; see attached image.
![image](https://github.com/user-attachments/assets/70ba3002-8e50-4aa0-b29c-fdf0d6ba0f8d)
